# Generated by Django 6.0.4 on 2026-04-16 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0003_initial'),
        ('inventory', '0002_initial'),
        ('locations', '0001_initial'),
        ('organizations', '0001_initial'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentmovement',
            name='moved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentmovement',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_movements', to='locations.location'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='actual_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='locations.location'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_inventory_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='scanned_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='tags.equipmenttag'),
        ),
        migrations.AddField(
            model_name='inventorysession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorysession',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_sessions', to='organizations.legalentity'),
        ),
        migrations.AddField(
            model_name='inventorysession',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_sessions', to='locations.location'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorysession'),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='organizations.legalentity'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('session', 'equipment')},
        ),
    ]
