# Generated by Django 6.0.4 on 2026-05-06 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_equipmentinventory_equipmentrepair'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='actual_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='warehouses.warehouse'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='condition_status',
            field=models.CharField(choices=[('ok', 'В рабочем состоянии'), ('needs_repair', 'Требует ремонта'), ('broken', 'Не работает'), ('written_off', 'К списанию')], default='ok', max_length=30),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='inventorysession',
            name='act_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='inventorysession',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inventorysession',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorysession',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_inventory_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorysession',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorysession',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
