# Generated by Django 6.0.4 on 2026-05-06 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventoryitem_actual_warehouse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentrepair',
            options={'ordering': ['-created_at', '-repair_date']},
        ),
        migrations.AddField(
            model_name='equipmentrepair',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentrepair',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_equipment_repairs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentrepair',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_equipment_repairs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentrepair',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentrepair',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('critical', 'Критический')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='equipmentrepair',
            name='resolution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='equipmentrepair',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentrepair',
            name='status',
            field=models.CharField(choices=[('requested', 'Заявка создана'), ('accepted', 'Принято техником'), ('in_progress', 'В работе'), ('waiting_parts', 'Ожидает запчасти'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='requested', max_length=30),
        ),
        migrations.AddField(
            model_name='equipmentrepair',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentrepair',
            name='status_comment',
            field=models.TextField(blank=True),
        ),
    ]
