# Generated by Django 6.0.4 on 2026-05-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_can_edit_accesses_user_can_edit_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('system_admin', 'System Admin'), ('company_admin', 'Company Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('auditor', 'Auditor'), ('technician', 'Technician'), ('service_engineer', 'Service Engineer')], default='staff', max_length=50),
        ),
    ]
