# Generated by Django 6.0.4 on 2026-05-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('system_admin', 'Системный администратор'), ('company_admin', 'Администратор компании'), ('manager', 'Менеджер'), ('staff', 'Сотрудник'), ('auditor', 'Аудитор'), ('technician', 'Техник'), ('service_engineer', 'Сервисный инженер')], default='staff', max_length=50),
        ),
    ]
