# Generated by Django 6.0.4 on 2026-05-05 01:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('archive', 'Архивирование'), ('delete', 'Удаление'), ('move', 'Перемещение'), ('reveal', 'Раскрытие секрета'), ('export', 'Экспорт'), ('login', 'Вход'), ('other', 'Другое')], max_length=30, verbose_name='Действие')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='ID объекта')),
                ('object_repr', models.CharField(blank=True, max_length=500, verbose_name='Объект')),
                ('message', models.TextField(blank=True, verbose_name='Описание')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Метаданные')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'Журнал действия',
                'verbose_name_plural': 'Журнал действий',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='core_action_created_96e063_idx'), models.Index(fields=['actor', 'created_at'], name='core_action_actor_i_fe4584_idx'), models.Index(fields=['action', 'created_at'], name='core_action_action_81059c_idx'), models.Index(fields=['content_type', 'object_id'], name='core_action_content_cd8876_idx')],
            },
        ),
    ]
