# Generated by Django 6.0.4 on 2026-04-16 17:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('brand', models.CharField(blank=True, max_length=255, verbose_name='Бренд')),
                ('model', models.CharField(blank=True, max_length=255, verbose_name='Модель')),
                ('serial_number', models.CharField(blank=True, max_length=255, verbose_name='Серийный номер')),
                ('inventory_number', models.CharField(blank=True, max_length=255, verbose_name='Инвентарный номер')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата покупки')),
                ('warranty_until', models.DateField(blank=True, null=True, verbose_name='Гарантия до')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория оборудования',
                'verbose_name_plural': 'Категории оборудования',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Статус оборудования',
                'verbose_name_plural': 'Статусы оборудования',
                'ordering': ['name'],
            },
        ),
    ]
