# Generated by Django 6.0.4 on 2026-04-16 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('locations', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='cost_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_items', to='organizations.costcenter', verbose_name='ЦФО'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_items', to='organizations.legalentity', verbose_name='Юридическое лицо'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_items', to='locations.location', verbose_name='Локация'),
        ),
    ]
