# Generated by Django 6.0.4 on 2026-05-04 16:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_notes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='equipment.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Заметка оборудования',
                'verbose_name_plural': 'Заметки оборудования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('file', models.FileField(upload_to='equipment_files/', verbose_name='Файл')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='equipment.equipment', verbose_name='Оборудование')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_equipment_files', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Файл оборудования',
                'verbose_name_plural': 'Файлы оборудования',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['equipment', 'is_active'], name='equipment_e_equipme_9bb9be_idx')],
            },
        ),
        migrations.CreateModel(
            name='EquipmentRequisite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requisite_type', models.CharField(choices=[('ip', 'IP'), ('mac', 'MAC'), ('domain', 'Домен'), ('hostname', 'Hostname'), ('url', 'URL'), ('other', 'Прочее')], default='ip', max_length=30, verbose_name='Тип')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('value', models.CharField(max_length=500, verbose_name='Значение')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_equipment_requisites', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisites', to='equipment.equipment', verbose_name='Оборудование')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_equipment_requisites', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Реквизит оборудования',
                'verbose_name_plural': 'Реквизиты оборудования',
                'ordering': ['requisite_type', 'name', 'value'],
                'indexes': [models.Index(fields=['equipment', 'is_active'], name='equipment_e_equipme_adbdc6_idx'), models.Index(fields=['requisite_type'], name='equipment_e_requisi_12f290_idx')],
            },
        ),
    ]
