# Generated by Django 6.0.4 on 2026-05-05 01:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_equipmentnote_equipmentfile_equipmentrequisite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='equipment_photos/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основное фото')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='equipment.equipment', verbose_name='Оборудование')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_equipment_photos', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Фото оборудования',
                'verbose_name_plural': 'Фото оборудования',
                'ordering': ['-is_primary', '-uploaded_at'],
                'indexes': [models.Index(fields=['equipment', 'is_active'], name='equipment_e_equipme_d8532a_idx'), models.Index(fields=['equipment', 'is_primary'], name='equipment_e_equipme_cf4ea5_idx')],
            },
        ),
    ]
