# Generated by Django 6.0.4 on 2026-05-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_equipmentphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='estimated_current_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Оценочная текущая стоимость'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='last_inventory_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последней инвентаризации'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='last_repair_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего ремонта'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='placement_zone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Зона размещения'),
        ),
    ]
