# Generated by Django 6.0.4 on 2026-07-10 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_equipment_estimated_current_value_and_more'),
        ('locations', '0001_initial'),
        ('organizations', '0004_alter_userlegalentityaccess_access_level_and_more'),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_items', to='equipment.equipmentcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_items', to='organizations.costcenter', verbose_name='ЦФО'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_items', to='organizations.legalentity', verbose_name='Юридическое лицо'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_items', to='locations.location', verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_items', to='equipment.equipmentstatus', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_items', to='warehouses.warehouse', verbose_name='Склад'),
        ),
    ]
