from django.urls import path
from .views import (
    dashboard_home,
    global_search_view,
    notifications_view,
    patch_notes_view,
    equipment_list_view,
    equipment_detail_view,
    equipment_export_csv_view,
    equipment_report_export_view,
    equipment_access_archive_view,
    equipment_access_create_view,
    equipment_access_detail_view,
    equipment_access_export_csv_view,
    equipment_access_list_view,
    equipment_access_update_view,
    equipment_file_archive_view,
    equipment_file_create_view,
    equipment_inventory_create_view,
    equipment_add_to_inventory_session_view,
    equipment_note_create_view,
    equipment_photo_archive_view,
    equipment_photo_create_view,
    equipment_photo_make_primary_view,
    equipment_repair_create_view,
    equipment_repair_update_view,
    equipment_requisite_archive_view,
    equipment_requisite_create_view,
    inventory_report_export_csv_view,
    inventory_report_export_view,
    access_user_report_view,
    access_secret_create_view,
    access_secret_reveal_view,
    access_secret_rotate_view,
    access_secret_archive_view,
    access_grant_create_view,
    access_grant_archive_view,
    movement_journal_view,
    movement_report_export_view,
    repair_request_list_view,
    repair_report_export_csv_view,
    repair_report_export_view,
    reports_home_view,
    tag_redirect_view,
    qr_print_view,
    qr_print_pdf_view,
    equipment_move_view,
    equipment_create_view,
    equipment_update_view,
    equipment_archive_view,
    equipment_regenerate_qr_view,
    inventory_item_check_view,
    inventory_session_add_item_view,
    inventory_session_confirm_view,
    inventory_session_create_view,
    inventory_session_detail_view,
    inventory_session_list_view,
    inventory_session_print_view,
    inventory_session_scan_item_view,
    cost_centers_by_location_view,
    warehouses_by_cost_center_view,
)
from .admin_views import (
    admin_panel_home,
    admin_section_create,
    admin_section_delete,
    admin_section_list,
    admin_section_update,
    audit_log_view,
)

urlpatterns = [
    path('', dashboard_home, name='dashboard_home'),
    path('patches/', patch_notes_view, name='patch_notes'),
    path('search/', global_search_view, name='global_search'),
    path('notifications/', notifications_view, name='notifications'),
    path('admin-panel/', admin_panel_home, name='admin_panel_home'),
    path('admin-panel/audit/', audit_log_view, name='audit_log'),
    path('admin-panel/<slug:section>/', admin_section_list, name='admin_section_list'),
    path('admin-panel/<slug:section>/create/', admin_section_create, name='admin_section_create'),
    path('admin-panel/<slug:section>/<str:pk>/edit/', admin_section_update, name='admin_section_update'),
    path('admin-panel/<slug:section>/<str:pk>/delete/', admin_section_delete, name='admin_section_delete'),
    path('ajax/cost-centers/', cost_centers_by_location_view, name='ajax_cost_centers'),
    path('ajax/warehouses/', warehouses_by_cost_center_view, name='ajax_warehouses'),
    path('equipment/', equipment_list_view, name='equipment_list'),
    path('equipment/export.csv', equipment_export_csv_view, name='equipment_export_csv'),
    path('accesses/', equipment_access_list_view, name='equipment_access_list'),
    path('accesses/export.csv', equipment_access_export_csv_view, name='equipment_access_export_csv'),
    path('accesses/users/', access_user_report_view, name='access_user_report'),
    path('reports/', reports_home_view, name='reports_home'),
    path('reports/equipment.csv', equipment_report_export_view, {'report_format': 'csv'}, name='equipment_report_export_csv'),
    path('reports/equipment.xlsx', equipment_report_export_view, {'report_format': 'xlsx'}, name='equipment_report_export_xlsx'),
    path('reports/equipment.pdf', equipment_report_export_view, {'report_format': 'pdf'}, name='equipment_report_export_pdf'),
    path('reports/repairs.csv', repair_report_export_csv_view, name='repair_report_export_csv'),
    path('reports/repairs.xlsx', repair_report_export_view, {'report_format': 'xlsx'}, name='repair_report_export_xlsx'),
    path('reports/repairs.pdf', repair_report_export_view, {'report_format': 'pdf'}, name='repair_report_export_pdf'),
    path('reports/inventory.csv', inventory_report_export_csv_view, name='inventory_report_export_csv'),
    path('reports/inventory.xlsx', inventory_report_export_view, {'report_format': 'xlsx'}, name='inventory_report_export_xlsx'),
    path('reports/inventory.pdf', inventory_report_export_view, {'report_format': 'pdf'}, name='inventory_report_export_pdf'),
    path('reports/movements.csv', movement_report_export_view, {'report_format': 'csv'}, name='movement_report_export_csv'),
    path('reports/movements.xlsx', movement_report_export_view, {'report_format': 'xlsx'}, name='movement_report_export_xlsx'),
    path('reports/movements.pdf', movement_report_export_view, {'report_format': 'pdf'}, name='movement_report_export_pdf'),
    path('accesses/create/', equipment_access_create_view, name='equipment_access_create'),
    path('accesses/<uuid:pk>/', equipment_access_detail_view, name='equipment_access_detail'),
    path('accesses/<uuid:pk>/edit/', equipment_access_update_view, name='equipment_access_update'),
    path('accesses/<uuid:pk>/archive/', equipment_access_archive_view, name='equipment_access_archive'),
    path('accesses/<uuid:pk>/secrets/add/', access_secret_create_view, name='access_secret_create'),
    path('accesses/<uuid:pk>/secrets/<uuid:secret_pk>/reveal/', access_secret_reveal_view, name='access_secret_reveal'),
    path('accesses/<uuid:pk>/secrets/<uuid:secret_pk>/rotate/', access_secret_rotate_view, name='access_secret_rotate'),
    path('accesses/<uuid:pk>/secrets/<uuid:secret_pk>/archive/', access_secret_archive_view, name='access_secret_archive'),
    path('accesses/<uuid:pk>/grants/add/', access_grant_create_view, name='access_grant_create'),
    path('accesses/<uuid:pk>/grants/<uuid:grant_pk>/archive/', access_grant_archive_view, name='access_grant_archive'),
    path('movements/', movement_journal_view, name='movement_journal'),
    path('repairs/', repair_request_list_view, name='repair_request_list'),
    path('inventory/', inventory_session_list_view, name='inventory_session_list'),
    path('inventory/create/', inventory_session_create_view, name='inventory_session_create'),
    path('inventory/<uuid:pk>/', inventory_session_detail_view, name='inventory_session_detail'),
    path('inventory/<uuid:pk>/add-item/', inventory_session_add_item_view, name='inventory_session_add_item'),
    path('inventory/<uuid:pk>/scan/', inventory_session_scan_item_view, name='inventory_session_scan_item'),
    path('inventory/<uuid:pk>/confirm/', inventory_session_confirm_view, name='inventory_session_confirm'),
    path('inventory/<uuid:pk>/print/', inventory_session_print_view, name='inventory_session_print'),
    path('inventory/<uuid:pk>/items/<uuid:item_pk>/check/', inventory_item_check_view, name='inventory_item_check'),
    path('equipment/<uuid:pk>/', equipment_detail_view, name='equipment_detail'),
    path('equipment/<uuid:pk>/notes/add/', equipment_note_create_view, name='equipment_note_create'),
    path('equipment/<uuid:pk>/requisites/add/', equipment_requisite_create_view, name='equipment_requisite_create'),
    path('equipment/<uuid:pk>/requisites/<uuid:requisite_pk>/archive/', equipment_requisite_archive_view, name='equipment_requisite_archive'),
    path('equipment/<uuid:pk>/files/add/', equipment_file_create_view, name='equipment_file_create'),
    path('equipment/<uuid:pk>/files/<uuid:file_pk>/archive/', equipment_file_archive_view, name='equipment_file_archive'),
    path('equipment/<uuid:pk>/photos/add/', equipment_photo_create_view, name='equipment_photo_create'),
    path('equipment/<uuid:pk>/photos/<uuid:photo_pk>/archive/', equipment_photo_archive_view, name='equipment_photo_archive'),
    path('equipment/<uuid:pk>/photos/<uuid:photo_pk>/make-primary/', equipment_photo_make_primary_view, name='equipment_photo_make_primary'),
    path('equipment/<uuid:pk>/repairs/add/', equipment_repair_create_view, name='equipment_repair_create'),
    path('repairs/<uuid:pk>/edit/', equipment_repair_update_view, name='equipment_repair_update'),
    path('equipment/<uuid:pk>/inventory/add/', equipment_inventory_create_view, name='equipment_inventory_create'),
    path('equipment/<uuid:pk>/inventory-session/add/', equipment_add_to_inventory_session_view, name='equipment_add_to_inventory_session'),
    path('tag/<str:code>/', tag_redirect_view, name='tag_redirect'),
    path('qr-print/', qr_print_view, name='qr_print'),
    path('qr-print-pdf/', qr_print_pdf_view, name='qr_print_pdf'),
    path('equipment/<uuid:pk>/move/', equipment_move_view, name='equipment_move'),
    path('equipment/<uuid:pk>/edit/', equipment_update_view, name='equipment_update'),
    path('equipment/<uuid:pk>/archive/', equipment_archive_view, name='equipment_archive'),
    path('equipment/<uuid:pk>/regenerate-qr/', equipment_regenerate_qr_view, name='equipment_regenerate_qr'),
    path('equipment/create/', equipment_create_view, name='equipment_create'),
]
