# Generated by Django 6.0.4 on 2026-04-16 17:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_type', models.CharField(choices=[('QR', 'QR Code'), ('NFC', 'NFC Tag'), ('BARCODE', 'Barcode'), ('RFID', 'RFID')], max_length=20)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('uid', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', models.TextField(blank=True)),
                ('payload_format', models.CharField(choices=[('url', 'URL'), ('uuid', 'UUID'), ('text', 'Text'), ('json', 'JSON')], default='uuid', max_length=20)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
