# Generated by Django 6.0.4 on 2026-04-16 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0003_initial'),
        ('organizations', '0002_initial'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenttag',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmenttag',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='equipmenttag',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_tags', to='organizations.legalentity'),
        ),
        migrations.AddIndex(
            model_name='equipmenttag',
            index=models.Index(fields=['code'], name='tags_equipm_code_da11bc_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmenttag',
            index=models.Index(fields=['uid'], name='tags_equipm_uid_548c0e_idx'),
        ),
        migrations.AddIndex(
            model_name='equipmenttag',
            index=models.Index(fields=['tag_type'], name='tags_equipm_tag_typ_3f7012_idx'),
        ),
    ]
