# Generated by Django 6.0.4 on 2026-05-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttag',
            name='tag_type',
            field=models.CharField(choices=[('QR', 'QR-код'), ('NFC', 'NFC-метка'), ('BARCODE', 'Штрихкод'), ('RFID', 'RFID')], max_length=20),
        ),
    ]
