# Generated by Django 6.0.4 on 2026-07-10 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_userlegalentityaccess_access_level_and_more'),
        ('tags', '0003_alter_equipmenttag_tag_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmenttag',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_tags', to='organizations.legalentity'),
        ),
    ]
