# Generated by Django 6.0.4 on 2026-05-04 10:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0003_initial'),
        ('locations', '0001_initial'),
        ('organizations', '0003_userlocationaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('host', models.CharField(blank=True, max_length=255)),
                ('port', models.PositiveIntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_accesses', to='accesses.accesstype')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_accesses', to='organizations.costcenter')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_equipment_accesses', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accesses', to='equipment.equipment')),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_accesses', to='organizations.legalentity')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_accesses', to='locations.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_equipment_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['legal_entity', 'location'], name='accesses_eq_legal_e_4b09e0_idx'), models.Index(fields=['equipment'], name='accesses_eq_equipme_a21490_idx'), models.Index(fields=['access_type'], name='accesses_eq_access__05c2f1_idx'), models.Index(fields=['is_active'], name='accesses_eq_is_acti_ca6a90_idx'), models.Index(fields=['expires_at'], name='accesses_eq_expires_5909d7_idx')],
            },
        ),
    ]
