# Generated by Django 6.0.4 on 2026-05-04 11:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentaccess',
            name='last_secret_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AccessSecret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret_type', models.CharField(choices=[('password', 'Password'), ('private_key', 'Private key'), ('token', 'Token'), ('recovery_code', 'Recovery code'), ('note', 'Secret note')], max_length=30)),
                ('label', models.CharField(max_length=255)),
                ('encrypted_value', models.TextField()),
                ('encryption_version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secrets', to='accesses.equipmentaccess')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_access_secrets', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_access_secrets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['secret_type', 'label'],
            },
        ),
        migrations.CreateModel(
            name='AccessSecretViewLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('result', models.CharField(choices=[('allowed', 'Allowed'), ('denied', 'Denied')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secret_view_logs', to='accesses.equipmentaccess')),
                ('secret', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='view_logs', to='accesses.accesssecret')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_secret_view_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='accesssecret',
            index=models.Index(fields=['access', 'is_active'], name='accesses_ac_access__aba999_idx'),
        ),
        migrations.AddIndex(
            model_name='accesssecret',
            index=models.Index(fields=['secret_type'], name='accesses_ac_secret__d7f2d1_idx'),
        ),
        migrations.AddIndex(
            model_name='accesssecretviewlog',
            index=models.Index(fields=['access', 'viewed_at'], name='accesses_ac_access__f227cd_idx'),
        ),
        migrations.AddIndex(
            model_name='accesssecretviewlog',
            index=models.Index(fields=['secret', 'viewed_at'], name='accesses_ac_secret__3095bd_idx'),
        ),
        migrations.AddIndex(
            model_name='accesssecretviewlog',
            index=models.Index(fields=['user', 'viewed_at'], name='accesses_ac_user_id_92fd1d_idx'),
        ),
        migrations.AddIndex(
            model_name='accesssecretviewlog',
            index=models.Index(fields=['result'], name='accesses_ac_result_140ae8_idx'),
        ),
    ]
