# Generated by Django 6.0.4 on 2026-05-04 12:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0002_equipmentaccess_last_secret_viewed_at_accesssecret_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('archived', 'Archived'), ('secret_added', 'Secret added'), ('secret_rotated', 'Secret rotated'), ('secret_archived', 'Secret archived')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_logs', to='accesses.equipmentaccess')),
                ('secret', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_logs', to='accesses.accesssecret')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['access', 'created_at'], name='accesses_ac_access__f58021_idx'), models.Index(fields=['secret', 'created_at'], name='accesses_ac_secret__3350d8_idx'), models.Index(fields=['user', 'created_at'], name='accesses_ac_user_id_214d9b_idx'), models.Index(fields=['action'], name='accesses_ac_action_fdbd97_idx')],
            },
        ),
    ]
