# Generated by Django 6.0.4 on 2026-05-04 12:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0003_accesschangelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesschangelog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('archived', 'Archived'), ('secret_added', 'Secret added'), ('secret_rotated', 'Secret rotated'), ('secret_archived', 'Secret archived'), ('grant_added', 'Grant added'), ('grant_archived', 'Grant archived')], max_length=30),
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('view_meta', 'View metadata'), ('view_secret', 'View secrets'), ('edit', 'Edit'), ('admin', 'Admin')], max_length=30)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='accesses.equipmentaccess')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_access_grants', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
                'indexes': [models.Index(fields=['access', 'is_active'], name='accesses_ac_access__9dbed4_idx'), models.Index(fields=['user', 'is_active'], name='accesses_ac_user_id_9977c8_idx'), models.Index(fields=['level'], name='accesses_ac_level_97331e_idx'), models.Index(fields=['expires_at'], name='accesses_ac_expires_f2fcce_idx')],
                'unique_together': {('user', 'access')},
            },
        ),
    ]
