# Generated by Django 6.0.4 on 2026-05-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesses', '0004_alter_accesschangelog_action_accessgrant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessgrant',
            name='level',
            field=models.CharField(choices=[('view_meta', 'Просмотр карточки'), ('view_secret', 'Просмотр секретов'), ('edit', 'Редактирование'), ('admin', 'Администрирование')], max_length=30),
        ),
        migrations.AlterField(
            model_name='accesssecret',
            name='secret_type',
            field=models.CharField(choices=[('password', 'Пароль'), ('private_key', 'Приватный ключ'), ('token', 'Токен'), ('recovery_code', 'Код восстановления'), ('note', 'Секретная заметка')], max_length=30),
        ),
    ]
