# Generated by Django 6.0.4 on 2026-04-16 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userlegalentityaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_entity_accesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='costcenter',
            unique_together={('legal_entity', 'location', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='userlegalentityaccess',
            unique_together={('user', 'legal_entity')},
        ),
    ]
