# Generated by Django 6.0.4 on 2026-05-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_userlocationaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlegalentityaccess',
            name='access_level',
            field=models.CharField(choices=[('view', 'Просмотр'), ('edit', 'Редактирование'), ('admin', 'Администрирование')], default='view', max_length=20),
        ),
        migrations.AlterField(
            model_name='userlocationaccess',
            name='access_level',
            field=models.CharField(choices=[('view', 'Просмотр'), ('edit', 'Редактирование'), ('admin', 'Администрирование')], default='view', max_length=20),
        ),
    ]
